# LEMP PLAYBOOK
---
- name: Install prerequisites
  hosts: www
  user: "{{ sudo_user }}"
  become: true
  vars_files:
    - group_vars/main.yml
    - vars/main.yml
  tasks:
    - name: "Add repository for PHP 8.1"
      apt_repository: "repo='ppa:ondrej/php'"

- name: LEMP Provisioning
  hosts: www
  user: "{{ sudo_user }}"
  become: true
  vars_files:
    - group_vars/main.yml
    - vars/main.yml
  roles:
    - geerlingguy.nginx
#    - geerlingguy.certbot
    - geerlingguy.php
#    - geerlingguy.mysql
#    - geerlingguy.php-mysql
#    - geerlingguy.memcached
#    - geerlingguy.git
#    - geerlingguy.composer
#    - geerlingguy.nodejs
